apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netai-chatbot.fullname" . }}-secrets
  labels:
    {{- include "netai-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  PERFSONAR_API_KEY: {{ .Values.secrets.perfsonarApiKey | quote }}
