{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netai-chatbot.serviceAccountName" . }}
  labels:
    {{- include "netai-chatbot.labels" . | nindent 4 }}
{{- end }}
